# Generated by Django 6.0.3 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('group', models.CharField(max_length=50, verbose_name='Група')),
                ('math_grade', models.IntegerField(verbose_name='Оцінка з математики')),
                ('programming_grade', models.IntegerField(verbose_name='Оцінка з програмування')),
                ('english_grade', models.IntegerField(verbose_name='Оцінка з англійської')),
            ],
        ),
    ]
